name: Auto Translate README

on:
  push:
    paths:
      - 'README.md' # Executa quando o README principal for alterado

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Traduzir README
        uses: ephraimduncan/translate-readme@v1 # Exemplo de Action de tradução
        with:
          LANG: 'es,fr,pt-br' # Idiomas de destino desejados
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
