name: Translate README

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Translate README
        uses: joshuacurtiss/translate-readme@v1
        with:
          target_lang: en, fr
          github_token: ${{ secrets.GITHUB_TOKEN }}
