name: Translate README

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que a Action faça commit e push no repositório

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Translate README
        uses: Lin-jun-xiang/action-translate-readme@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          langs: en,fr
